# api-gateway servisine özel konfigürasyon
server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: identity-service-auth
              uri: lb://IDENTITY-SERVICE
              predicates:
                - Path=/api/v1/auth/**
            - id: identity-service-users
              uri: lb://IDENTITY-SERVICE
              predicates:
                - Path=/api/v1/users/**
            - id: customer-service
              uri: lb://CUSTOMER-SERVICE
              predicates:
                - Path=/api/v1/customers/**
            - id: product-catalog-service
              uri: lb://PRODUCT-CATALOG-SERVICE
              predicates:
                - Path=/api/v1/products/**
  data:
    redis:
      host: localhost
      port: 6379

telcox:
  gateway:
    rate-limit:
      requests-per-minute: 100
    public-paths:
      - pattern: /api/v1/auth/**
      - pattern: /actuator/**
      - pattern: /eureka/**
      - pattern: /*/v3/api-docs/**
      - pattern: /*/swagger-ui/**
      - pattern: /*/swagger-ui.html
      - pattern: /api/v1/customers
        method: POST
      - pattern: /api/v1/products/**
        method: GET
