server:
  port: 9007

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/billing_db
    username: telcox
    password: telcox
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
