# product-catalog-service'e özel konfigürasyon
server:
  port: 9003

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/product_catalog_db
    username: telcox
    password: telcox
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 600000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
