apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: telco-crm
data:
  01-create-databases.sql: |
    CREATE DATABASE identity_db;
    CREATE DATABASE customer_db;
    CREATE DATABASE product_catalog_db;
    CREATE DATABASE order_db;
    CREATE DATABASE subscription_db;
    CREATE DATABASE usage_db;
    CREATE DATABASE billing_db;
    CREATE DATABASE payment_db;
    CREATE DATABASE notification_db;
    CREATE DATABASE ticket_db;
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: telco-crm
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: telco-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: telcox
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: telcox-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: telcox
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "telcox"]
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: init-scripts
          configMap:
            name: postgres-init
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: telco-crm
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
